version: '3.2'

volumes:
  trquake_postgres: {}


services:
  django:
    container_name: trquake-app
    build:
      dockerfile: docker/development/Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=trquake.settings.development
      - POSTGRES_PASSWORD=debug
      - POSTGRES_USER=debug
      - POSTGRES_DB=debug
      - POSTGRES_HOST=trquake-database
      - POSTGRES_PORT=5432
    command:
      - /start-django

  database:
    image: postgres:15.1
    container_name: trquake-database
    environment:
      - POSTGRES_PASSWORD=debug
      - POSTGRES_USER=debug
      - POSTGRES_DB=debug
    volumes:
      - trquake_postgres:/var/lib/postgresql/data
