version: '3.2'

services:
  django: &django
    container_name: trquake-app
    image: trquake-app
    build:
      dockerfile: docker/development/Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command:
      - /start-django

  workers:
    <<: *django
    container_name: trquake-workers
    image: trquake-worker
    ports: []
    command: watchmedo auto-restart --directory=/app --pattern=*.py --recursive -- celery -A trquake.celery.app worker -B --concurrency=5 -l DEBUG
